output-class: Locales
arb-dir: lib/l10n/arb
template-arb-file: app_en.arb
synthetic-package: false
nullable-getter: false
output-dir: lib/l10n/gen
format: true
untranslated-messages-file: lib/l10n/untraslated_keys.json